name: Publish to Maven Central

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17 and cache Gradle
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          # Provide your GPG private key (base64‑encoded) and its passphrase.
          # (Make sure to update your secret name if needed.)
          gpg_key: ${{ secrets.SIGNING_SECRET_KEY }}
          passphrase: ${{ secrets.SIGNING_PASSWORD }}

      - name: Grant execute permission to gradlew
        run: chmod +x gradlew

      - name: Build and publish
        env:
          SONATYPE_HOST: CENTRAL_PORTAL
          RELEASE_SIGNING_ENABLED: true
          GROUP: io.github.mejdi14
          POM_ARTIFACT_ID: KMP-Searchable-Dropdown
          VERSION_NAME: ${{ github.ref_name }}  # Uses the tag name as version (e.g., v0.3.0)
          POM_NAME: KMP-Searchable-Dropdown
          POM_DESCRIPTION: "This library provides …"
          POM_URL: https://github.com/mejdi14/KMP-Searchable-Dropdown
          POM_LICENSE_NAME: "The Apache Software License, Version 2.0"
          POM_LICENSE_URL: https://www.apache.org/licenses/LICENSE-2.0.txt
          POM_LICENSE_DIST: repo
          POM_SCM_URL: https://github.com/mejdi14/KMP-Searchable-Dropdown
          POM_SCM_CONNECTION: scm:git:git://github.com/mejdi14/KMP-Searchable-Dropdown.git
          POM_SCM_DEV_CONNECTION: scm:git:ssh://git@github.com/mejdi14/KMP-Searchable-Dropdown.git
          POM_DEVELOPER_ID: mejdi14
          POM_DEVELOPER_NAME: "mejdi hafiene"
          POM_DEVELOPER_URL: https://github.com/mejdi14/
          POM_DEVELOPER_EMAIL: mejdihafiane@gmail.com
          mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          signing.keyId: ${{ secrets.SIGNING_KEY_ID }}
          signing.password: ${{ secrets.SIGNING_PASSWORD }}
        run: |
          # Clean, build, publish to Sonatype staging, then close and release the repository.
          ./gradlew clean build publishToSonatype closeAndReleaseRepository
