name: Publish to Maven Central

on:
  push:
    tags:
      - 'v*'  # Triggers on tags like v1.0.0, v0.3.0, etc.

jobs:
  publish:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Import GPG key
        run: |
          # Import the private key from the secret into the GPG keyring.
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
          # Set GPG_TTY so that GPG knows which terminal to use.
          export GPG_TTY=$(tty)
          # List keys for debugging (optional)
          gpg --list-secret-keys --keyid-format LONG
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Configure GPG for non-interactive mode
        run: |
          mkdir -p ~/.gnupg
          echo "no-tty" >> ~/.gnupg/gpg.conf

      - name: Grant execute permission to gradlew
        run: chmod +x gradlew

      - name: Build and Publish to Maven Central
        env:
          RELEASE_SIGNING_ENABLED: true
          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          # Optionally pass your key ID if needed (recommended to use the long key ID)
          signing.keyId: ${{ secrets.SIGNING_KEY_ID }}
        run: |
          # Run the Gradle publish task (our build is configured to use useGpgCmd())
          ./gradlew publish
