name: Publish to Maven Central

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission to gradlew
        run: chmod +x gradlew

      - name: Build and publish
        env:
          SONATYPE_HOST: CENTRAL_PORTAL
          RELEASE_SIGNING_ENABLED: false
          GROUP: io.github.mejdi14
          POM_ARTIFACT_ID: KMP-Searchable-Dropdown
          VERSION_NAME: ${{ github.ref_name }} # Use the tag name as the version (e.g., v0.3.0)
          POM_NAME: KMP-Searchable-Dropdown
          POM_DESCRIPTION: This library provides ....
          POM_URL: https://github.com/mejdi14/KMP-Searchable-Dropdown
          POM_LICENSE_NAME: The Apache Software License, Version 2.0
          POM_LICENSE_URL: https://www.apache.org/licenses/LICENSE-2.0.txt
          POM_LICENSE_DIST: repo
          POM_SCM_URL: https://github.com/mejdi14/KMP-Searchable-Dropdown
          POM_SCM_CONNECTION: scm:git:git://github.com/mejdi14/KMP-Searchable-Dropdown.git
          POM_SCM_DEV_CONNECTION: scm:git:ssh://git@github.com/mejdi14/KMP-Searchable-Dropdown.git
          POM_DEVELOPER_ID: mejdi14
          POM_DEVELOPER_NAME: mejdi hafiene
          POM_DEVELOPER_URL: https://github.com/mejdi14/
          POM_DEVELOPER_EMAIL: mejdihafiane@gmail.com
          mavenCentralUsername: AfqG1IXv # Hardcoded username
          mavenCentralPassword: 1p7xdMppb3mV1wI5FAz5ZiUVXBxnG+n4dpVR4LxyGhnR # Hardcoded password
          signing.keyId: B4893510 # Hardcoded key ID
          signing.password: Azma4everfuck14@ # Hardcoded signing password
          signing.secretKeyRingFile: mykeys.gpg # Path to the GPG key file in the root of the project
        run: |
          ./gradlew :searchableDropdown:assemble
          ./gradlew publishAllPublicationsToMavenCentralRepository --debug