name: Publish to Maven Central

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Grant execute permission to gradlew
        run: chmod +x gradlew

      - name: Import GPG Key
        run: |
          # Import the passphrase-free GPG private key into the keyring.
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
          # (Optional) List imported keys for debugging.
          gpg --list-secret-keys --keyid-format LONG
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Build and Publish to Maven Central
        env:
          # Non-sensitive properties
          android.nonTransitiveRClass: true
          SONATYPE_HOST: CENTRAL_PORTAL
          RELEASE_SIGNING_ENABLED: true
          GROUP: io.github.mejdi14
          POM_ARTIFACT_ID: KMP-Searchable-Dropdown
          POM_NAME: KMP-Searchable-Dropdown
          POM_DESCRIPTION: "This library provides ...."
          POM_URL: https://github.com/mejdi14/KMP-Searchable-Dropdown
          POM_LICENSE_NAME: "The Apache Software License, Version 2.0"
          POM_LICENSE_URL: https://www.apache.org/licenses/LICENSE-2.0.txt
          POM_LICENSE_DIST: repo
          POM_SCM_URL: https://github.com/mejdi14/KMP-Searchable-Dropdown
          POM_SCM_CONNECTION: scm:git:git://github.com/mejdi14/KMP-Searchable-Dropdown.git
          POM_SCM_DEV_CONNECTION: scm:git:ssh://git@github.com/mejdi14/KMP-Searchable-Dropdown.git
          POM_DEVELOPER_ID: mejdi14
          POM_DEVELOPER_NAME: "mejdi hafiene"
          POM_DEVELOPER_URL: https://github.com/mejdi14/
          POM_DEVELOPER_EMAIL: mejdihafiane@gmail.com


        run: |
          # Extract the version from the tag.
          # For a tag like "v0.0.2", this will remove the "refs/tags/v" prefix and the "v" so that VERSION_NAME becomes "0.0.2".
          VERSION_NAME=${GITHUB_REF#refs/tags/v}
          echo "Publishing version: $VERSION_NAME"
          
          # Pass the VERSION_NAME to Gradle as a project property
          ./gradlew publish -PVERSION_NAME="$VERSION_NAME"
