name: Publish to Maven Central

on:
  push:
    tags:
      - 'v*' # Trigger the workflow only when a tag starting with 'v' is pushed (e.g., v0.3.0)

jobs:
  publish:
    runs-on: macos-latest # Use macOS to build iOS targets
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.SIGNING_SECRET_KEY_RING_FILE }}
          passphrase: ${{ secrets.SIGNING_PASSWORD }}

      - name: Verify GPG key
        run: |
          gpg --list-keys

      - name: Grant execute permission to gradlew
        run: chmod +x gradlew

      - name: Build and publish
        env:
          SONATYPE_HOST: CENTRAL_PORTAL
          RELEASE_SIGNING_ENABLED: true
          GROUP: io.github.mejdi14
          POM_ARTIFACT_ID: KMP-Searchable-Dropdown
          VERSION_NAME: ${{ github.ref_name }} # Use the tag name as the version (e.g., v0.3.0)
          POM_NAME: KMP-Searchable-Dropdown
          POM_DESCRIPTION: This library provides ....
          POM_URL: https://github.com/mejdi14/KMP-Searchable-Dropdown
          POM_LICENSE_NAME: The Apache Software License, Version 2.0
          POM_LICENSE_URL: https://www.apache.org/licenses/LICENSE-2.0.txt
          POM_LICENSE_DIST: repo
          POM_SCM_URL: https://github.com/mejdi14/KMP-Searchable-Dropdown
          POM_SCM_CONNECTION: scm:git:git://github.com/mejdi14/KMP-Searchable-Dropdown.git
          POM_SCM_DEV_CONNECTION: scm:git:ssh://git@github.com/mejdi14/KMP-Searchable-Dropdown.git
          POM_DEVELOPER_ID: mejdi14
          POM_DEVELOPER_NAME: mejdi hafiene
          POM_DEVELOPER_URL: https://github.com/mejdi14/
          POM_DEVELOPER_EMAIL: mejdihafiane@gmail.com
          mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          signing.keyId: B4893510 # Use the short key ID
          signing.password: ${{ secrets.SIGNING_PASSWORD }}
          signing.secretKeyRingFile: /home/runner/.gnupg/private-keys-v1.d/*.key
        run: |
          ./gradlew :searchableDropdown:assemble --info
          ./gradlew publishAllPublicationsToMavenCentralRepository --info