name: Publish to Maven Central

on:
  push:
    tags:
      - 'v*' # Trigger the workflow only when a tag starting with 'v' is pushed (e.g., v0.3.0)

jobs:
  publish:
    runs-on: macos-latest # Use macOS to build iOS targets
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Decode GPG key
        run: |
          echo "${{ secrets.SIGNING_SECRET_KEY_RING_FILE }}" | base64 --decode > mykeys.gpg

      - name: Import GPG key
        env:
          GPG_TTY: /dev/null
        run: |
          gpg --batch --pinentry-mode loopback --import mykeys.gpg

      - name: Verify GPG key
        run: |
          gpg --list-keys

      - name: Grant execute permission to gradlew
        run: chmod +x gradlew

      - name: Build and publish
        env:
          SONATYPE_HOST: CENTRAL_PORTAL
          RELEASE_SIGNING_ENABLED: true